// Generated by CoffeeScript 1.3.3
/**
 * PSDのスマートオブジェクトをPNGに書き出し
 * version 1.0
*/

var $dialog, ControlUI, DialogUI, WindowUI, action, close, copy, createDocument, currentHeight, currentWidth, enlargeForSelect, extract, fileNameCounter, fileNames, getBounds, getLayerPath, getMetrics, nameCounter, offsetX, offsetY, originalHeight, originalWidth, output, outputCSS, outputJSON, outputLESS, paste, restoreDimension, saveFolder, saveJPEG, savePNG, select, structures, varDump,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

preferences.rulerUnits = Units.PIXELS;

originalWidth = 0;

originalHeight = 0;

currentWidth = 0;

currentHeight = 0;

offsetX = 0;

offsetY = 0;

saveFolder = null;

nameCounter = 0;

structures = [];

fileNames = {};

fileNameCounter = 0;

Number.prototype.fillZero = function(n) {
  var zeros;
  zeros = new Array(n + 1 - this.toString(10).length);
  return zeros.join('0') + this;
};

varDump = function(obj) {
  var _key, _rlt, _val;
  _rlt = [];
  for (_key in obj) {
    if (!__hasProp.call(obj, _key)) continue;
    try {
      _val = obj[_key];
      if (!(_val instanceof Function)) {
        _rlt.push(_key + ': ' + _val);
      }
    } catch (error) {

    }
  }
  return alert(_rlt.join('\n'));
};

ControlUI = (function() {

  function ControlUI($window, type, width, height, left, top, options) {
    this.$window = $window;
    this.type = type;
    this.width = width != null ? width : 100;
    this.height = height != null ? height : 20;
    this.left = left != null ? left : 0;
    this.top = top != null ? top : 0;
    if (options == null) {
      options = [];
    }
    this.window = this.$window.window;
    this.context = this.window.add.apply(this.window, [this.type, [this.left, this.top, this.width + this.left, this.height + this.top]].concat(options));
  }

  ControlUI.prototype.close = function(value) {
    return this.window.close(value);
  };

  ControlUI.prototype.val = function(getValue) {
    var type, value;
    switch (this.type) {
      case 'edittext':
      case 'statictext':
        type = 'text';
        break;
      default:
        type = 'value';
    }
    if (getValue != null) {
      this.context[type] = value = getValue.toString();
    } else {
      value = this.context[type];
    }
    return value;
  };

  ControlUI.prototype.on = function(event, callback) {
    var self,
      _this = this;
    event = event.toLowerCase().replace(/^on/i, '').replace(/^./, function(character) {
      return character.toUpperCase();
    });
    self = this;
    this.context['on' + event] = function() {
      return callback.apply(self, arguments);
    };
    return this;
  };

  return ControlUI;

})();

WindowUI = (function() {

  function WindowUI(type, name, width, height, options, callback) {
    var BUTTON_HEIGHT, BUTTON_MARGIN, BUTTON_WIDTH, stop;
    this.type = type;
    this.name = name != null ? name : 'ダイアログボックス';
    this.width = width != null ? width : 100;
    this.height = height != null ? height : 100;
    this.window = new Window(this.type, this.name, [0, 0, this.width, this.height], options);
    this.window.center();
    this.controls = [];
    this.onOK = function() {};
    this.onCancel = function() {};
    BUTTON_WIDTH = 100;
    BUTTON_HEIGHT = 20;
    BUTTON_MARGIN = 10;
    this.addButton('OK', BUTTON_WIDTH, BUTTON_HEIGHT, this.width - BUTTON_WIDTH - BUTTON_MARGIN, this.height - BUTTON_HEIGHT - BUTTON_MARGIN, {
      click: function() {
        return this.$window.onOK.apply(this, arguments);
      }
    });
    this.addButton('キャンセル', BUTTON_WIDTH, BUTTON_HEIGHT, this.width - BUTTON_WIDTH - BUTTON_MARGIN - BUTTON_WIDTH - BUTTON_MARGIN, this.height - BUTTON_HEIGHT - BUTTON_MARGIN, {
      click: function() {
        this.$window.onCancel.apply(this, arguments);
        return this.close();
      }
    });
    stop = callback != null ? callback.call(this) : void 0;
    if (stop !== false) {
      this.show();
    }
  }

  WindowUI.prototype.close = function(value) {
    return this.window.close(value);
  };

  WindowUI.prototype.show = function() {
    this.window.show();
    return this;
  };

  WindowUI.prototype.hide = function() {
    this.window.hide();
    return this;
  };

  WindowUI.prototype.center = function() {
    this.window.center();
    return this;
  };

  WindowUI.prototype.addControl = function(type, width, height, left, top, options, events) {
    var $ctrl, callback, event;
    $ctrl = new ControlUI(this, type, width, height, left, top, options);
    if (events != null) {
      for (event in events) {
        if (!__hasProp.call(events, event)) continue;
        callback = events[event];
        $ctrl.on(event, callback);
      }
    }
    this.controls.push($ctrl);
    return $ctrl;
  };

  WindowUI.prototype.addTextbox = function(width, height, left, top, defaultText, events) {
    if (defaultText == null) {
      defaultText = '';
    }
    return this.addControl('edittext', width, height, left, top, [defaultText], events);
  };

  WindowUI.prototype.addText = function(text, width, height, left, top, events) {
    if (text == null) {
      text = '';
    }
    return this.addControl('statictext', width, height, left, top, [text], events);
  };

  WindowUI.prototype.addButton = function(label, width, height, left, top, events) {
    return this.addControl('button', width, height, left, top, [label], events);
  };

  WindowUI.prototype.addRadio = function(label, width, height, left, top, events) {
    return this.addControl('radiobutton', width, height, left, top, [label], events);
  };

  WindowUI.prototype.addCheckbox = function(label, width, height, left, top, events) {
    return this.addControl('checkbox', width, height, left, top, [label], events);
  };

  WindowUI.prototype.ok = function(callback) {
    if (callback == null) {
      callback = function() {};
    }
    this.onOK = callback;
    return this;
  };

  WindowUI.prototype.cancel = function(callback) {
    if (callback == null) {
      callback = function() {};
    }
    this.onCancel = callback;
    return this;
  };

  return WindowUI;

})();

DialogUI = (function(_super) {

  __extends(DialogUI, _super);

  function DialogUI(name, width, height, options, callback) {
    this.name = name;
    this.width = width;
    this.height = height;
    DialogUI.__super__.constructor.call(this, 'dialog', this.name, this.width, this.height, options, callback);
  }

  return DialogUI;

})(WindowUI);

getLayerPath = function(layer) {
  var getLayerName, path;
  path = [];
  getLayerName = function(layer) {
    path.push(layer.name);
    if (layer.parent) {
      getLayerName(layer.parent);
    }
  };
  getLayerName(layer);
  path.shift();
  path.pop();
  path.pop();
  path.reverse();
  return encodeURI('/' + path.join('/'));
};

saveJPEG = function(fileName, folder, quality) {
  var jpegOpt, newFile;
  if (folder == null) {
    folder = '~';
  }
  if (quality == null) {
    quality = 12;
  }
  newFile = new File(folder + '/' + fileName);
  jpegOpt = new JPEGSaveOptions();
  jpegOpt.embedColorProfile = false;
  jpegOpt.quality = quality;
  jpegOpt.formatOptions = FormatOptions.OPTIMIZEDBASELINE;
  jpegOpt.scans = 3;
  jpegOpt.matte = MatteType.NONE;
  activeDocument.saveAs(newFile, jpegOpt, true, Extension.LOWERCASE);
};

savePNG = function(fileName, dir) {
  var exp, file, filePath, folder;
  if (dir == null) {
    dir = '';
  }
  exp = new ExportOptionsSaveForWeb;
  exp.format = SaveDocumentType.PNG;
  exp.interlaced = false;
  exp.PNG8 = false;
  folder = new Folder(saveFolder + dir + '/');
  if (!folder.exists) {
    folder.create();
  }
  filePath = folder + '/' + fileName + '.png';
  file = new File(filePath);
  activeDocument.exportDocument(file, ExportType.SAVEFORWEB, exp);
  return file.getRelativeURI(saveFolder);
};

close = function(showDialog) {
  if (showDialog == null) {
    showDialog = false;
  }
  if (showDialog) {
    if (!confirm('閉じてよろしいですか?')) {
      return;
    }
  }
  activeDocument.close(SaveOptions.DONOTSAVECHANGES);
};

getBounds = function(layer) {
  var bounds;
  bounds = layer.bounds;
  return {
    x: parseInt(bounds[0], 10),
    y: parseInt(bounds[1], 10),
    x2: parseInt(bounds[2], 10),
    y2: parseInt(bounds[3], 10)
  };
};

enlargeForSelect = function(layer) {
  var bounds;
  bounds = getBounds(layer);
  if (bounds.x < 0) {
    currentWidth -= bounds.x;
    offsetX += bounds.x;
    activeDocument.resizeCanvas(currentWidth, currentHeight, AnchorPosition.TOPRIGHT);
  }
  if (bounds.y < 0) {
    currentHeight -= bounds.y;
    offsetY += bounds.y;
    activeDocument.resizeCanvas(currentWidth, currentHeight, AnchorPosition.BOTTOMLEFT);
  }
  if (bounds.x2 > currentWidth + offsetX) {
    currentWidth += bounds.x2 + offsetX;
    activeDocument.resizeCanvas(currentWidth, currentHeight, AnchorPosition.TOPLEFT);
  }
  if (bounds.y2 > currentHeight + offsetY) {
    currentHeight += bounds.y2 + offsetY;
    activeDocument.resizeCanvas(currentWidth, currentHeight, AnchorPosition.TOPLEFT);
  }
  return getBounds(layer);
};

restoreDimension = function() {
  activeDocument.resizeCanvas(originalWidth - offsetX, originalHeight - offsetY, AnchorPosition.TOPLEFT);
  return activeDocument.resizeCanvas(originalWidth, originalHeight, AnchorPosition.BOTTOMRIGHT);
};

select = function(layer) {
  var bounds;
  bounds = enlargeForSelect(layer);
  activeDocument.selection.select([[bounds.x, bounds.y], [bounds.x2, bounds.y], [bounds.x2, bounds.y2], [bounds.x, bounds.y2]]);
};

copy = function(layer) {
  activeDocument.activeLayer = layer;
  activeDocument.selection.copy();
  activeDocument.selection.deselect();
};

paste = function(doc) {
  doc.paste();
};

getMetrics = function(layer) {
  var bounds;
  bounds = getBounds(layer);
  return {
    x: bounds.x + offsetX,
    y: bounds.y + offsetY,
    width: bounds.x2 - bounds.x,
    height: bounds.y2 - bounds.y
  };
};

createDocument = function(width, height, name) {
  return documents.add(width, height, 72, name, NewDocumentMode.RGB, DocumentFill.TRANSPARENT);
};

outputCSS = function(structures) {
  var html, i, layer, outputFile, outputText, text, z, _i, _j, _len, _len1;
  structures.reverse();
  outputText = [];
  for (i = _i = 0, _len = structures.length; _i < _len; i = ++_i) {
    layer = structures[i];
    z = 10000 - i * 10;
    text = "." + layer.name + " \{\n	position: absolute;\n	top: " + layer.y + "px;\n	left: " + layer.x + "px;\n	z-index: " + z + ";\n	width: " + layer.width + "px;\n	height: " + layer.height + "px;\n	background: url(" + layer.url + ") no-repeat scroll 0 0;\n\}";
    outputText.push(text);
  }
  outputFile = new File(saveFolder + '/' + 'style.css');
  outputFile.open('w');
  outputFile.encoding = 'utf-8';
  outputFile.write(outputText.join('\n'));
  outputFile.close();
  outputText = [];
  for (i = _j = 0, _len1 = structures.length; _j < _len1; i = ++_j) {
    layer = structures[i];
    text = "<div class=\"" + layer.name + "\"></div>";
    outputText.push(text);
  }
  html = "<!doctype html>\n<html>\n<head>\n	<meta charset=\"utf-8\">\n	<link rel=\"stylesheet\" href=\"style.css\">\n$\n</haed>\n<body>\n</body>\n</html>";
  outputFile = new File(saveFolder + '/' + 'index.html');
  outputFile.open('w');
  outputFile.encoding = 'utf-8';
  outputFile.write(html.replace('$', outputText.join('\n')));
  outputFile.close();
};

outputLESS = function(structures) {
  return alert('LESSはまだつくってない');
};

outputJSON = function(structures) {
  var i, layer, outputFile, outputText, text, vars, z, _i, _j, _len, _len1;
  structures.reverse();
  outputText = [];
  for (i = _i = 0, _len = structures.length; _i < _len; i = ++_i) {
    layer = structures[i];
    z = 10000 - i * 10;
    text = "\{\n	\"name\": \"" + layer.name + "\",\n	\"className\": \"" + layer.name + "\",\n	\"x\": " + layer.x + ",\n	\"y\": " + layer.y + ",\n	\"z\": " + z + ",\n	\"width\": " + layer.width + ",\n	\"height\": " + layer.height + ",\n	\"url\": \"" + layer.url + "\"\n\}";
    outputText.push(text);
  }
  outputFile = new File(saveFolder + '/' + 'structures.json');
  outputFile.open('w');
  outputFile.encoding = 'utf-8';
  outputFile.write('[' + outputText.join(',\n') + ']');
  outputFile.close();
  vars = [];
  for (i = _j = 0, _len1 = structures.length; _j < _len1; i = ++_j) {
    layer = structures[i];
    vars.push("$" + layer.name + " = $('<div class=\"" + layer.name + "\">')");
  }
  outputFile = new File(saveFolder + '/' + 'structures.js');
  outputFile.open('w');
  outputFile.encoding = 'utf-8';
  outputFile.write(';(function ($) {\n\nvar\n' + vars.join(',\n') + ';\n}(this.jQuery));');
  return outputFile.close();
};

extract = function(layer) {
  var data, dir, i, metrics, name, newDoc, parent, sub, url, _i, _j, _len, _len1, _ref, _ref1;
  parent = layer.parent;
  if (parent) {
    _ref = parent.layers;
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      sub = _ref[i];
      sub._v = sub.visible;
      sub.visible = false;
    }
  }
  layer.visible = true;
  name = layer.name.replace(/^[^a-z_-]/i, 'image').replace(/[^0-9a-z_-]/gi, '');
  if (name === 'image') {
    name = 'image_' + nameCounter++;
  }
  if (fileNames[name]) {
    name += fileNameCounter++;
  }
  fileNames[name] = true;
  select(layer);
  copy(layer);
  metrics = getMetrics(layer);
  newDoc = createDocument(metrics.width, metrics.height, layer.name);
  paste(newDoc);
  dir = getLayerPath(layer);
  url = savePNG(name, dir);
  newDoc.close(SaveOptions.DONOTSAVECHANGES);
  data = metrics;
  data.name = name;
  data.url = url;
  structures.push(data);
  parent = layer.parent;
  if (parent) {
    _ref1 = parent.layers;
    for (i = _j = 0, _len1 = _ref1.length; _j < _len1; i = ++_j) {
      sub = _ref1[i];
      sub.visible = sub._v;
    }
  }
};

output = function(layers) {
  var i, layer, _i, _len;
  for (i = _i = 0, _len = layers.length; _i < _len; i = ++_i) {
    layer = layers[i];
    if (layer.typename === 'LayerSet') {
      output(layer.layers);
    } else {
      if (layer.visible && layer.kind === LayerKind.SMARTOBJECT) {
        extract(layer);
      }
    }
  }
};

action = function(typeFlag, saveFolderPath) {
  var FLAG_CSS, FLAG_JQUERY, FLAG_LESS, layers;
  if (saveFolderPath == null) {
    saveFolderPath = '~/';
  }
  originalWidth = activeDocument.width;
  originalHeight = activeDocument.height;
  currentWidth = originalWidth;
  currentHeight = originalHeight;
  saveFolder = new Folder(saveFolderPath);
  layers = activeDocument.layers;
  output(layers);
  restoreDimension();
  FLAG_CSS = 1;
  FLAG_LESS = 2;
  FLAG_JQUERY = 4;
  if (typeFlag & FLAG_CSS) {
    outputCSS(structures);
  }
  if (typeFlag & FLAG_LESS) {
    outputLESS(structures);
  }
  if (typeFlag & FLAG_JQUERY) {
    outputJSON(structures);
  }
};

$dialog = new DialogUI('PSD to PNG', 700, 400, null, function() {
  var $saveFolder, $types;
  this.addText('書き出しフォルダ', 120, 20, 10, 50);
  $saveFolder = this.addTextbox(540, 20, 60, 70);
  this.addButton('選択', 80, 20, 610, 70, {
    click: function() {
      saveFolder = Folder.selectDialog('保存先のフォルダを選択してください');
      return $saveFolder.val(decodeURI(saveFolder.getRelativeURI('/')));
    }
  });
  this.addText('書き出し形式', 120, 20, 10, 160);
  $types = [];
  $types.push(this.addCheckbox('HTML&CSS', 220, 20, 10, 190));
  $types.push(this.addCheckbox('LESS', 220, 20, 230, 190));
  $types.push(this.addCheckbox('jQuery', 220, 20, 450, 190));
  return this.ok(function() {
    var $type, i, saveFolderPath, typeFlag, _i, _len;
    saveFolderPath = encodeURI($saveFolder.val());
    typeFlag = 0;
    for (i = _i = 0, _len = $types.length; _i < _len; i = ++_i) {
      $type = $types[i];
      if ($type.val()) {
        typeFlag += Math.pow(2, i);
      }
    }
    this.close();
    return action(typeFlag, saveFolderPath);
  });
});
